- link:
    ~/.Brewfile: brew/personal

- brewfile:
    - ~/.Brewfile

- shell:
    - [brew bundle cleanup --global --zap --force, Cleanup unused brew packages]
    - [mas upgrade, Upgrading applications installed via App Store]
    - [brew cu -afy, Force upgrade brew cask applications]
