- shell:
    - [mkdir -p ~/.ssh/master, Creating SSH ControlMaster directory]
    - [mkdir -p ~/.ssh/config.d, Creating SSH Config Subdir]
    - 
        command: source install/ssh-keys.sh
        stdin: true
        stderr: true
        stdout: true
        description: Install SSH Keys
- link:
    ~/.ssh/config: ssh/config
