# init zplug
if [[ ! -d ~/.zplug ]];then
    git clone https://github.com/zplug/zplug ~/.zplug
fi

if [[ -z "$ZPLUG_HOME" ]]; then
    export ZPLUG_HOME=~/.zplug
fi
source $ZPLUG_HOME/init.zsh

# theme
zplug 'denysdovhan/spaceship-prompt', use:spaceship.zsh, from:github, as:theme
SPACESHIP_PROMPT_ORDER=(
    user
    dir
    git
    aws
    venv
    pyenv
    terraform
    exec_time
    line_sep
    jobs
    exit_code
    char
)

SPACESHIP_RPROMPT_ORDER=(
    time
)

SPACESHIP_TIME_SHOW=true
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_PROMPT_ADD_NEWLINE=false

zplug 'zsh-users/zsh-syntax-highlighting', defer:2
zplug 'zsh-users/zsh-history-substring-search', defer:3
zplug 'zdharma/history-search-multi-word', defer:3
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions', depth:1
zplug 'zpm-zsh/material-colors'


# oh-my-zsh plugins
zplug 'lib/clipboard', from:oh-my-zsh
zplug 'plugins/asdf', from:oh-my-zsh
zplug 'plugins/brew', from:oh-my-zsh
zplug 'plugins/colored-man-pages', from:oh-my-zsh
zplug 'plugins/colorize', from:oh-my-zsh
zplug 'plugins/command-not-found', from:oh-my-zsh
zplug 'plugins/docker', from:oh-my-zsh
zplug 'plugins/docker-compose', from:oh-my-zsh
#zplug 'plugins/git', from:oh-my-zsh
zplug 'plugins/gnu-utils', from:oh-my-zsh
zplug 'plugins/sudo', from:oh-my-zsh
zplug 'plugins/terraform', from:oh-my-zsh

# prezto-plugins
zplug 'modules/osx', from:prezto
zstyle ':prezto:module:ssh:load' identities 'id_rsa.personal' 'id_rsa.work'
zplug 'modules/ssh', from:prezto


# binaries / commands
zplug 'asdf-vm/asdf', use:asdf.sh
zplug 'dandavison/delta', as:command, from:gh-r
zplug 'junegunn/fzf', use:'shell/*.zsh'
zplug 'junegunn/fzf-bin', as:command, from:gh-r, rename-to:fzf
zplug 'paulirish/git-open', as:plugin
zplug 'rupa/z', use:z.sh
zplug 'stedolan/jq', as:command, from:gh-r, rename-to:jq
zplug 'wfxr/forgit'
zplug 'denilsonsa/prettyping', as:command
zplug 'eivindArvesen/prm', as:command, use:prm.sh, hook-load:"alias prm='source prm.sh'"

FORGIT_LOG_GRAPH_ENABLE=false

if ! zplug check --verbose; then
    printf 'Install? [y/N]: '
    if read -q; then
        echo; zplug install
    fi
fi
zplug load

# history settings
HISTSIZE=50000              #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=99999999           #Number of history entries to save to disk
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

EDITOR=vim

# aliases
source ~/.zsh/aliases.zsh

# use rg for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob \!.git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# source asdf
# ~/.zplug/repos/asdf-vm/asdf/
source ~/.zplug/repos/asdf-vm/asdf/asdf.sh
